import groovy.json.JsonSlurperClassic
import Build

pipeline {
    
    agent any
    
    environment {
        dockerRegistry = "ghcr.io"
        dockerOwner = "maksimenkavn"        
//      id_buld = $BUILD_ID
        app_API = "maksimenkavn/time-app-api-dev"
        app_FRONT = "maksimenkavn/time-app-frontend-dev"
        dockerImageTagAPI = "${dockerOwner}/${app_API}"
        dockerImageTagFRONT = "${dockerOwner}/${app_FRONT}"
        dockerRemoveTag = "${dockerRegistry}/${dockerOwner}/${app}:${old_number}"
    }

    stages {
        stage('Stop Services') {
            steps {
                sh """    
                docker stop maksimenkavn/time-app-frontend-dev           
                docker stop maksimenkavn/time-app-api-dev
                docker stop adminer
                docker stop mysql
                docker system prune -f                                
                docker rmi -f ${app_API}
                docker rmi -f ${app_FRONT}             
                """
            }
        }

        stage('Build API') {
            steps {
                script {
                    path = 'time/time-app/api'
                }
                sh """                                               
                docker build -t ${app_API} -f ${path}/Dockerfile ${path}
                """
            }
        }

        stage('Build FRONT') {
            steps {
                script {
                    path = 'time/time-app/frontend'
                }
                sh "docker build -t ${app_FRONT} -f ${path}/Dockerfile ${path}"
            }
        }

        stage('Test') {
            steps {
                sh "echo Test"                
            }
        }        
 
        stage('Push image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DockerHubCredentials', passwordVariable: 'pass', usernameVariable: 'maksimenkavn')]) {
                    sh """echo ${pass} | docker login ${dockerRegistry} -u ${user} --password-stdin
                    docker push ${dockerImageTagAPI}
                    docker push ${dockerImageTagFRONT}
                    """
                }
            }
        }

        stage('Start Services') {
            steps {
                sh """
                  ls -la
                  pwd
                  echo "Build# $BUILD_ID"
                  docker-compose -f ./time/time-app/docker-compose-pub.yml up -d
                """
            }
        }

    }
    post {
        always {
            cleanWs()
        }
    }
}