version: '3'

services:
  frontend:
    image: maksimenkavn/time-app-frontend-dev
    restart: always
    ports:
      - '3000:3000'
  api:
    image: maksimenkavn/time-app-api-dev
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    
  mysql:
    image: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  mysql_data_pub: